spring.application.name=estage-backend
spring.jpa.defer-datasource-initialization=true
spring.servlet.multipart.max-file-size=10MB

# Taille maximale de la requ?te totale (ici, 100 M?gaoctets)
spring.servlet.multipart.max-request-size=100MB

# Augmente le nombre maximum de "parties" (champs + fichiers) dans une requ?te multipart.
#spring.servlet.multipart.max-request-parts=20

api.python.cv-analysis.url=http://127.0.0.1:8000/analyse-cv/

# Activer la console web de H2
#spring.h2.console.enabled=true

# (Optionnel mais recommand?) D?finir un chemin personnalis? pour la console
#spring.h2.console.path=/h2-console

# --- Configuration du Serveur d'Email (SMTP) avec Gmail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=papoukalory@gmail.com
spring.mail.password=fqsn jsly znhk qohj

# Propri?t?s suppl?mentaires pour la connexion s?curis?e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.from.name=e-Stage BEAC Recrutement

#spring.data.mongodb.uri=mongodb+srv://papoukalory:MonMotDePasseFacile123@cluster0.gsamykv.mongodb.net/

spring.data.mongodb.uri=mongodb://localhost:27017

# 2. Le nom de la base de donn?es que vous voulez utiliser.

spring.data.mongodb.database=estage-beac-db


# Cl? API pour le service Google Gemini
#gemini.api.key=AIzaSyDaPtJNhb10_XIN8H1YFSRD2LPGOlIMFb0